services:
  application:
    container_name: shortcircuit.shadowo.lol
    image: mcr.microsoft.com/dotnet/aspnet:9.0
    user: app
    build: 
      context: /app
      target: /app
    command: bash -c "cd /app && dotnet ShortCircuit.Server.dll"
    environment:
      - HTTP_PORTS=8080
      - HTTPS_PORTS=8081
    expose:
      - 8081
    volumes:
      - ${APP_PATH}:/app
    networks:
      - local
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - internet
      - local

networks:
  local:
    driver: bridge
    internal: true
  internet:
    driver: bridge